apiVersion: apps/v1
kind: Deployment
metadata:
  name: gridappsd
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: gridappsd
  name: gridappsd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gridappsd
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.service.expose: "true"
        kompose.service.type: nodeport
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: gridappsd
    spec:
      containers:
        - env:
            - name: DEBUG
              value: "1"
            - name: LD_LIBRARY_PATH
              value: /usr/local/lib64
            - name: PATH
              value: /gridappsd/bin:/gridappsd/lib:/gridappsd/services/fncsgossbridge/service:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
          image: gridappsd/gridappsd:develop
          name: gridappsd
          ports:
            - containerPort: 61613
            - containerPort: 61614
            - containerPort: 61616
            - containerPort: 20000
            - containerPort: 20001
            - containerPort: 20002
            - containerPort: 20003
            - containerPort: 20004
            - containerPort: 20005
            - containerPort: 20006
            - containerPort: 20007
            - containerPort: 20008
            - containerPort: 20009
            - containerPort: 20010
            - containerPort: 20011
            - containerPort: 20012
            - containerPort: 20013
            - containerPort: 20014
            - containerPort: 20015
            - containerPort: 20016
            - containerPort: 20017
            - containerPort: 20018
            - containerPort: 20019
            - containerPort: 20020
            - containerPort: 8000
            - containerPort: 8888
          resources: {}
          workingDir: /gridappsd
      restartPolicy: Always
status: {}
