apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: proven
  name: proven
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proven
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: proven
    spec:
      containers:
        - env:
            - name: PROVEN_IDB_DB
              value: proven
            - name: PROVEN_IDB_PASSWORD
              value: root
            - name: PROVEN_IDB_RP
              value: autogen
            - name: PROVEN_IDB_URL
              value: http://influxdb:8086
            - name: PROVEN_IDB_USERNAME
              value: root
            - name: PROVEN_SERVICES_PORT
              value: "18080"
            - name: PROVEN_SWAGGER_HOST_PORT
              value: localhost:18080
            - name: PROVEN_T3DIR
              value: /proven
            - name: PROVEN_USE_IDB
              value: "true"
          image: gridappsd/proven:develop
          name: proven
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
