{{- if .Values.gridappsd.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gridappsd.serviceAccountName" . }}
  labels:
    {{- include "gridappsd.labels" . | nindent 4 }}
  {{- with .Values.gridappsd.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.gridappsd.serviceAccount.automount }}
{{- end }}
